2022-08-04 13:10:01,225 ERROR: Exception on / [GET] [in C:\Users\rsingh\AppData\Roaming\Python\Python310\site-packages\flask\app.py:1509]
Traceback (most recent call last):
  File "C:\Users\rsingh\AppData\Roaming\Python\Python310\site-packages\sqlalchemy\engine\base.py", line 1770, in _execute_context
    self.dialect.do_execute(
  File "C:\Users\rsingh\AppData\Roaming\Python\Python310\site-packages\sqlalchemy\engine\default.py", line 717, in do_execute
    cursor.execute(statement, parameters)
sqlite3.OperationalError: no such table: user

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\rsingh\AppData\Roaming\Python\Python310\site-packages\flask\app.py", line 2276, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\rsingh\AppData\Roaming\Python\Python310\site-packages\flask\app.py", line 1589, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\rsingh\AppData\Roaming\Python\Python310\site-packages\flask\app.py", line 1585, in full_dispatch_request
    rv = self.preprocess_request()
  File "C:\Users\rsingh\AppData\Roaming\Python\Python310\site-packages\flask\app.py", line 2060, in preprocess_request
    rv = self.ensure_sync(before_func)()
  File "C:\Learning\SEL\Wk\Code\CMU-SOEN-Microblog-Assignment-Repo\app\main\routes.py", line 17, in before_request
    if current_user.is_authenticated:
  File "C:\Users\rsingh\AppData\Roaming\Python\Python310\site-packages\werkzeug\local.py", line 422, in __get__
    obj = instance._get_current_object()
  File "C:\Users\rsingh\AppData\Roaming\Python\Python310\site-packages\werkzeug\local.py", line 544, in _get_current_object
    return self.__local()  # type: ignore
  File "C:\Users\rsingh\AppData\Roaming\Python\Python310\site-packages\flask_login\utils.py", line 26, in <lambda>
    current_user = LocalProxy(lambda: _get_user())
  File "C:\Users\rsingh\AppData\Roaming\Python\Python310\site-packages\flask_login\utils.py", line 346, in _get_user
    current_app.login_manager._load_user()
  File "C:\Users\rsingh\AppData\Roaming\Python\Python310\site-packages\flask_login\login_manager.py", line 318, in _load_user
    user = self._user_callback(user_id)
  File "C:\Learning\SEL\Wk\Code\CMU-SOEN-Microblog-Assignment-Repo\app\models.py", line 239, in load_user
    return None
  File "<string>", line 2, in get
  File "C:\Users\rsingh\AppData\Roaming\Python\Python310\site-packages\sqlalchemy\util\deprecations.py", line 390, in warned
    return fn(*args, **kwargs)
  File "C:\Users\rsingh\AppData\Roaming\Python\Python310\site-packages\sqlalchemy\orm\query.py", line 942, in get
    return self._get_impl(ident, loading.load_on_pk_identity)
  File "C:\Users\rsingh\AppData\Roaming\Python\Python310\site-packages\sqlalchemy\orm\query.py", line 946, in _get_impl
    return self.session._get_impl(
  File "C:\Users\rsingh\AppData\Roaming\Python\Python310\site-packages\sqlalchemy\orm\session.py", line 2839, in _get_impl
    return db_load_fn(
  File "C:\Users\rsingh\AppData\Roaming\Python\Python310\site-packages\sqlalchemy\orm\loading.py", line 531, in load_on_pk_identity
    session.execute(
  File "C:\Users\rsingh\AppData\Roaming\Python\Python310\site-packages\sqlalchemy\orm\session.py", line 1689, in execute
    result = conn._execute_20(statement, params or {}, execution_options)
  File "C:\Users\rsingh\AppData\Roaming\Python\Python310\site-packages\sqlalchemy\engine\base.py", line 1582, in _execute_20
    return meth(self, args_10style, kwargs_10style, execution_options)
  File "C:\Users\rsingh\AppData\Roaming\Python\Python310\site-packages\sqlalchemy\sql\elements.py", line 323, in _execute_on_connection
    return connection._execute_clauseelement(
  File "C:\Users\rsingh\AppData\Roaming\Python\Python310\site-packages\sqlalchemy\engine\base.py", line 1451, in _execute_clauseelement
    ret = self._execute_context(
  File "C:\Users\rsingh\AppData\Roaming\Python\Python310\site-packages\sqlalchemy\engine\base.py", line 1813, in _execute_context
    self._handle_dbapi_exception(
  File "C:\Users\rsingh\AppData\Roaming\Python\Python310\site-packages\sqlalchemy\engine\base.py", line 1994, in _handle_dbapi_exception
    util.raise_(
  File "C:\Users\rsingh\AppData\Roaming\Python\Python310\site-packages\sqlalchemy\util\compat.py", line 207, in raise_
    raise exception
  File "C:\Users\rsingh\AppData\Roaming\Python\Python310\site-packages\sqlalchemy\engine\base.py", line 1770, in _execute_context
    self.dialect.do_execute(
  File "C:\Users\rsingh\AppData\Roaming\Python\Python310\site-packages\sqlalchemy\engine\default.py", line 717, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) no such table: user
[SQL: SELECT user.id AS user_id, user.username AS user_username, user.email AS user_email, user.password_hash AS user_password_hash, user.about_me AS user_about_me, user.last_seen AS user_last_seen, user.token AS user_token, user.token_expiration AS user_token_expiration, user.last_message_read_time AS user_last_message_read_time 
FROM user 
WHERE user.id = ?]
[parameters: (1,)]
(Background on this error at: http://sqlalche.me/e/14/e3q8)
2022-08-10 10:49:36,454 INFO: Microblog startup [in C:\Learning\SEL\Wk\Code\CMU-SOEN-Microblog-Assignment-Repo\app\__init__.py:89]
2022-08-10 10:49:39,041 INFO: Microblog startup [in C:\Learning\SEL\Wk\Code\CMU-SOEN-Microblog-Assignment-Repo\app\__init__.py:89]
2022-08-10 10:49:53,319 INFO: Microblog startup [in C:\Learning\SEL\Wk\Code\CMU-SOEN-Microblog-Assignment-Repo\app\__init__.py:89]
2022-08-10 14:25:21,479 INFO: Microblog startup [in C:\Learning\SEL\Wk\Code\CMU-SOEN-Microblog-Assignment-Repo\app\__init__.py:89]
2022-08-17 10:04:43,674 INFO: Microblog startup [in C:\Learning\SEL\Wk\Code\CMU-SOEN-Microblog-Assignment-Repo\app\__init__.py:89]
2022-08-17 10:04:48,974 INFO: Microblog startup [in C:\Learning\SEL\Wk\Code\CMU-SOEN-Microblog-Assignment-Repo\app\__init__.py:89]
2022-08-17 10:05:00,779 INFO: Microblog startup [in C:\Learning\SEL\Wk\Code\CMU-SOEN-Microblog-Assignment-Repo\app\__init__.py:89]
2022-08-17 10:05:38,253 INFO: Microblog startup [in C:\Learning\SEL\Wk\Code\CMU-SOEN-Microblog-Assignment-Repo\app\__init__.py:89]
